"""Add session mode

Revision ID: 419efffec5b0
Revises: a1b2c3d4e5f6
Create Date: 2026-05-30 00:25:26.031425
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419efffec5b0'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('triage_sessions', sa.Column('mode', sa.String(length=20), nullable=False, server_default='patient'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triage_sessions', 'mode')
    # ### end Alembic commands ###
