"""Add has_expressed_sympathy to TriageSession

Revision ID: 8456e3cd4241
Revises: 
Create Date: 2026-04-29 11:28:12.874419
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8456e3cd4241'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_messages_session_id'), table_name='messages')
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.alter_column('model_audits', 'structured_output_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('idx_model_audits_session_id'), table_name='model_audits')
    op.create_index(op.f('ix_model_audits_session_id'), 'model_audits', ['session_id'], unique=False)
    op.drop_index(op.f('idx_rule_events_session_id'), table_name='rule_events')
    op.create_index(op.f('ix_rule_events_session_id'), 'rule_events', ['session_id'], unique=False)
    op.drop_index(op.f('idx_session_facts_session_id'), table_name='session_facts')
    op.drop_constraint(op.f('session_facts_session_id_key'), 'session_facts', type_='unique')
    op.create_index(op.f('ix_session_facts_session_id'), 'session_facts', ['session_id'], unique=True)
    op.add_column('triage_sessions', sa.Column('has_expressed_sympathy', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triage_sessions', 'has_expressed_sympathy')
    op.drop_index(op.f('ix_session_facts_session_id'), table_name='session_facts')
    op.create_unique_constraint(op.f('session_facts_session_id_key'), 'session_facts', ['session_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_session_facts_session_id'), 'session_facts', ['session_id'], unique=False)
    op.drop_index(op.f('ix_rule_events_session_id'), table_name='rule_events')
    op.create_index(op.f('idx_rule_events_session_id'), 'rule_events', ['session_id'], unique=False)
    op.drop_index(op.f('ix_model_audits_session_id'), table_name='model_audits')
    op.create_index(op.f('idx_model_audits_session_id'), 'model_audits', ['session_id'], unique=False)
    op.alter_column('model_audits', 'structured_output_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.create_index(op.f('idx_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###
